"""baseline

The schema as it stood before Alembic was introduced.

Databases that predate Alembic adopt it with `alembic stamp 0001`, which
records this revision as applied WITHOUT running it. Only a genuinely empty
database should ever run this upgrade -- on an existing one it would fail
trying to CREATE TABLE users.

Revision ID: 0001
Revises:
Create Date: 2026-08-02 20:27:10.857467
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_index('ix_folders_user_id_created_at', 'folders', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_folders_user_id_updated_at', 'folders', ['user_id', 'updated_at'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_folder_id'), 'notes', ['folder_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index('ix_notes_user_id_date', 'notes', ['user_id', 'date'], unique=False)
    op.create_index('ix_notes_user_id_is_deleted_date', 'notes', ['user_id', 'is_deleted', 'date'], unique=False)
    op.create_index('ix_notes_user_id_updated_at', 'notes', ['user_id', 'updated_at'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('note_id', sa.String(length=36), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_note_id'), 'artifacts', ['note_id'], unique=False)
    op.create_index(op.f('ix_artifacts_user_id'), 'artifacts', ['user_id'], unique=False)
    op.create_table('artifact_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_comments_artifact_id'), 'artifact_comments', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_comments_user_id'), 'artifact_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_comments_user_id'), table_name='artifact_comments')
    op.drop_index(op.f('ix_artifact_comments_artifact_id'), table_name='artifact_comments')
    op.drop_table('artifact_comments')
    op.drop_index(op.f('ix_artifacts_user_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_note_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_notes_user_id_updated_at', table_name='notes')
    op.drop_index('ix_notes_user_id_is_deleted_date', table_name='notes')
    op.drop_index('ix_notes_user_id_date', table_name='notes')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_folder_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_folders_user_id_updated_at', table_name='folders')
    op.drop_index('ix_folders_user_id_created_at', table_name='folders')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
