"""add revision

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-02 20:28:48.316380
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_comments', sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
    op.add_column('artifacts', sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
    op.add_column('folders', sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
    op.add_column('notes', sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'revision')
    op.drop_column('folders', 'revision')
    op.drop_column('artifacts', 'revision')
    op.drop_column('artifact_comments', 'revision')
    # ### end Alembic commands ###
