"""add revision

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-02 20:28:48.316380
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table: str, column: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return column in {c["name"] for c in inspector.get_columns(table)}


def upgrade() -> None:
    # Skips a column that is already there, because `init_db()` runs
    # `Base.metadata.create_all()` on every app start: a database whose tables
    # were first created by a build that already had `revision` in the models
    # arrives here with the column present, and a blind add_column would abort
    # the whole upgrade on "column already exists".
    for table in ('artifact_comments', 'artifacts', 'folders', 'notes'):
        if not _has_column(table, 'revision'):
            op.add_column(
                table,
                sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'revision')
    op.drop_column('folders', 'revision')
    op.drop_column('artifacts', 'revision')
    op.drop_column('artifact_comments', 'revision')
    # ### end Alembic commands ###
