"""folder members

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-02 22:18:14.408248
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Skipped when the table is already there: `init_db()` runs
    # `Base.metadata.create_all()` on every app start, so any database the app
    # has booted against since FolderMember joined the models already has this
    # table, and create_table would abort the upgrade on "already exists".
    if 'folder_members' in sa.inspect(op.get_bind()).get_table_names():
        return

    op.create_table('folder_members',
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id', 'user_id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_members')
    # ### end Alembic commands ###
